name: Java CI

on: 
  push: 
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 01 - Copy program To Runner
        uses: actions/checkout@v2
        
      - name: 02 - Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          
      - name: 03 - Build with Ant
        run: ant -noinput -buildfile build.xml
